services:
  generator:
    image: daily-greeting:dev
    build:
      context: .
      network: host
    container_name: daily-greeting-generator
    volumes:
      - ./data:/data
      - ./config.yaml:/config/config.yaml
      - greeting-models:/models
    env_file:
      - path: .env
        required: false
    network_mode: host

volumes:
  greeting-models:
